### ISSUE TITLE
Feature request:  "forever24" functionality

### ISSUE THREAD

**Issue by rsilva712** [cppisking/ffrk-inspector#62]
Possibly a limited request, i guess it depends on how many more survival events are coming down the line, but is this something that can be incorporated into inspector, rather than having to run 2 separate programs and all the port swapping involved with the clients?

Why is this useful?  
Just like the original, you can use it to target specific mobs or paths. Say you dont want to risk double Anima in your heroic runs, or maybe you want to target a specific path for your hard runs. Or, as this event has shown, you can farm a specific mob for orbs.

Maybe it's as easy as a drop down that can be added, or perhaps a text field to manually enter the target mob? Idk

**Comment by cppisking** [comment]
I know a lot of people want this, and I also realize how useful it is from a practical standpoint.  On the other hand, I really don't want to open the can of worms that is involved with manipulating or controlling the data stream sent from the client to the server.  

What happens if they put some logic in their server to detect how fast a client is sending requests, and if it's faster than some measure they deem achievable through regular user interaction, they ban the user?  I don't want any part of that.

Morality issues aside, I just don't want FFRK Inspector to be even **possible** to be mistaken for a bot.  Look, but don't touch.
