### ISSUE TITLE
Feature Request: Enemy info in battle drop window

### ISSUE THREAD

**Issue by karryt** [cppisking/ffrk-inspector#68]
Kind of inspired by this request: http://www.reddit.com/r/FFRecordKeeper/comments/38jp65/is_there_a_way_to_find_out_what_level_of_atk_or/

Are you considering adding additional info to the battle window? This doesn't totally fit in to the existing drop window or stage info window, but if you could calculate and show the minimum ATK or MAG stat needed to one shot monsters in each stage that could be very helpful for farming purposes. If we add this though I could see how having some other info could be helpful like enemy HP, elemental weaknesses, etc but not sure how cluttered it would be, as after all, the app is foremost about collecting drop info.

Totally unrelated, is there a way to send a PM via Reddit or through Github? I'm new to both and haven't found a way to do so?

**Comment by karryt** [comment]
Haha, I wrote that up and then went to get a glass of milk and now it's mostly a duplicate of this request submitted a few minutes before me!

https://github.com/cppisking/ffrk-inspector/issues/67

**Comment by cppisking** [comment]
on reddit you can send a PM.  Not on github.  On reddit go to my user page and in the top right under my karma counts there's an almost impossibly small "send message" link.

And yea, really weird coincidence about this feature request :)  I'll close this one since I already commented on the other one.
